//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitePoint.Cookbook.Configuration {
    
    public partial class RetrieveAppSetting {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Label appSettingValue;
		protected System.Web.UI.WebControls.Label connStr;
		protected System.Web.UI.WebControls.Label lblMyStuff;
    }
}
